import "dotenv/config";
import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { v4 as uuid } from "uuid";
import PDFDocument from "pdfkit";
import { initialiseStore, readDb, updateDb } from "./store.js";

const app = express();
const port = Number(process.env.PORT || 4000);
const jwtSecret = process.env.JWT_SECRET || "development-only-change-me";
const allowedOrigins = (process.env.CLIENT_URL || "http://localhost:5173").split(",").map((value) => value.trim());
// Vite may select 5174, 5175, etc. when its default port is occupied.
// Permit localhost development ports while retaining the explicit production allow-list.
app.use(cors({
  origin(origin, callback) {
    const localDevelopmentOrigin = /^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin || "");
    if (!origin || allowedOrigins.includes(origin) || localDevelopmentOrigin) return callback(null, true);
    return callback(new Error("Origin is not allowed by CORS"));
  },
}));
app.use(express.json({ limit: "1mb" }));

const publicProject = (project) => ({ ...project, fundingProgress: project.budgetCr ? Math.round((project.releasedCr / project.budgetCr) * 100) : 0, executionGap: Math.round((project.releasedCr / project.budgetCr) * 100 - project.physicalProgress) });
const riskScore = (project) => Math.min(100, Math.max(0, Math.round(project.scheduleLagDays * 1.3 + Math.max(0, project.targetProgress - project.physicalProgress) * 1.8 + Math.max(0, (project.releasedCr / project.budgetCr) * 100 - project.physicalProgress) * 1.5)));
const tokenFor = (user) => jwt.sign({ sub: user.id, email: user.email, role: user.role }, jwtSecret, { expiresIn: "8h" });
function requireAuth(req, res, next) { const token = req.headers.authorization?.replace(/^Bearer\s+/i, ""); if (!token) return res.status(401).json({ message: "Authentication required" }); try { req.user = jwt.verify(token, jwtSecret); next(); } catch { res.status(401).json({ message: "Invalid or expired token" }); } }
function ensureProject(db, id, res) { const project = db.projects.find((item) => item.id === id); if (!project) { res.status(404).json({ message: "Project not found" }); return null; } return project; }
function validateProject(body, partial = false) { const required = ["id", "name", "department", "location", "budgetCr"]; const missing = required.filter((key) => !partial && (body[key] === undefined || body[key] === "")); if (missing.length) return `Missing required fields: ${missing.join(", ")}`; if (body.budgetCr !== undefined && (!Number.isFinite(Number(body.budgetCr)) || Number(body.budgetCr) < 0)) return "budgetCr must be a non-negative number"; return null; }
const validPercent = (value, label) => Number.isFinite(Number(value)) && Number(value) >= 0 && Number(value) <= 100 ? null : `${label} must be between 0 and 100`;
const detailFor = (db, project) => ({ ...publicProject(project), healthIndex: riskScore(project), milestones: db.milestones.filter((item) => item.projectId === project.id).sort((a, b) => String(a.dueDate || "").localeCompare(String(b.dueDate || ""))), auditSignals: db.auditSignals.filter((item) => item.projectId === project.id), issues: (db.issues || []).filter((item) => item.projectId === project.id), alerts: db.alerts.filter((item) => item.projectId === project.id), progressHistory: db.progressUpdates.filter((item) => item.projectId === project.id) });

app.get("/api/health", (_req, res) => res.json({ status: "ok", service: "projectpulse-api", timestamp: new Date().toISOString() }));
app.post("/api/auth/login", async (req, res) => { const { email, password } = req.body; if (!email || !password) return res.status(400).json({ message: "email and password are required" }); const user = readDb().users.find((item) => item.email.toLowerCase() === String(email).toLowerCase()); if (!user || !(await bcrypt.compare(password, user.passwordHash))) return res.status(401).json({ message: "Invalid email or password" }); res.json({ token: tokenFor(user), user: { id: user.id, name: user.name, email: user.email, role: user.role } }); });
app.get("/api/auth/me", requireAuth, (req, res) => { const user = readDb().users.find((item) => item.id === req.user.sub); res.json({ id: user.id, name: user.name, email: user.email, role: user.role }); });

app.get("/api/dashboard", requireAuth, (_req, res) => { const db = readDb(); const projects = db.projects.map(publicProject); const counts = { total: projects.length, onTrack: projects.filter((p) => ["Low", "On Track"].includes(p.risk)).length, atRisk: projects.filter((p) => ["Medium", "High", "At Risk"].includes(p.risk)).length, critical: projects.filter((p) => p.risk === "Critical").length }; const average = (field) => projects.length ? +(projects.reduce((sum, p) => sum + Number(p[field] || 0), 0) / projects.length).toFixed(1) : 0; res.json({ metrics: counts, execution: { physicalProgress: average("physicalProgress"), fundingProgress: average("fundingProgress") }, attentionProjects: projects.filter((p) => p.risk !== "Low").sort((a, b) => riskScore(b) - riskScore(a)).slice(0, 10), latestAlert: db.alerts.find((alert) => alert.status === "Open") || null }); });
app.get("/api/projects", requireAuth, (req, res) => { const { q = "", risk, status } = req.query; let projects = readDb().projects; const search = String(q).toLowerCase(); if (search) projects = projects.filter((p) => [p.id, p.name, p.department, p.location].join(" ").toLowerCase().includes(search)); if (risk) projects = projects.filter((p) => p.risk === risk); if (status) projects = projects.filter((p) => p.status === status); res.json({ data: projects.map(publicProject), total: projects.length }); });
app.post("/api/projects", requireAuth, (req, res) => { const error = validateProject(req.body); if (error) return res.status(400).json({ message: error }); const created = updateDb((db) => { if (db.projects.some((p) => p.id === req.body.id)) throw new Error("Project ID already exists"); const time = new Date().toISOString(); const project = { id: String(req.body.id), name: req.body.name, department: req.body.department, location: req.body.location, status: req.body.status || "In Progress", risk: req.body.risk || "Low", budgetCr: Number(req.body.budgetCr), releasedCr: Number(req.body.releasedCr || 0), physicalProgress: Number(req.body.physicalProgress || 0), targetProgress: Number(req.body.targetProgress || 0), scheduleLagDays: Number(req.body.scheduleLagDays || 0), estimatedCompletion: req.body.estimatedCompletion || null, revisedCompletion: req.body.revisedCompletion || null, createdAt: time, updatedAt: time }; db.projects.push(project); return project; }); res.status(201).json(publicProject(created)); });
app.get("/api/projects/:id", requireAuth, (req, res) => { const db = readDb(); const project = ensureProject(db, req.params.id, res); if (project) res.json(detailFor(db, project)); });
app.patch("/api/projects/:id", requireAuth, (req, res) => { const error = validateProject(req.body, true); if (error) return res.status(400).json({ message: error }); const updated = updateDb((db) => { const project = ensureProject(db, req.params.id, res); if (!project) return null; Object.assign(project, Object.fromEntries(Object.entries(req.body).filter(([key]) => !["id", "createdAt"].includes(key))), { updatedAt: new Date().toISOString() }); ["budgetCr", "releasedCr", "physicalProgress", "targetProgress", "scheduleLagDays"].forEach((key) => { if (project[key] !== undefined) project[key] = Number(project[key]); }); return project; }); if (updated) res.json(publicProject(updated)); });
app.delete("/api/projects/:id", requireAuth, (req, res) => { const removed = updateDb((db) => { const index = db.projects.findIndex((p) => p.id === req.params.id); if (index < 0) return false; db.projects.splice(index, 1); ["milestones", "auditSignals", "alerts", "progressUpdates"].forEach((collection) => { db[collection] = db[collection].filter((item) => item.projectId !== req.params.id); }); return true; }); if (!removed) return res.status(404).json({ message: "Project not found" }); res.status(204).end(); });

app.get("/api/projects/:id/progress", requireAuth, (req, res) => { const db = readDb(); if (ensureProject(db, req.params.id, res)) res.json({ data: db.progressUpdates.filter((item) => item.projectId === req.params.id) }); });
app.post("/api/projects/:id/progress", requireAuth, (req, res) => { const { overallProgress, physicalProgress, financialProgress, phase, summary = "", remarks = "", updatedBy = req.user.sub, date = new Date().toISOString().slice(0, 10) } = req.body; const error = validPercent(overallProgress, "Overall progress") || validPercent(physicalProgress, "Physical progress") || validPercent(financialProgress, "Financial progress"); if (error || !phase || !updatedBy) return res.status(400).json({ message: error || "Phase and Updated By are required" }); const update = updateDb((db) => { const project = ensureProject(db, req.params.id, res); if (!project) return null; project.physicalProgress = Number(physicalProgress); project.releasedCr = project.budgetCr ? Math.round(project.budgetCr * Number(financialProgress) / 100) : project.releasedCr; project.updatedAt = new Date().toISOString(); const entry = { id: uuid(), projectId: project.id, overallProgress: Number(overallProgress), physicalProgress: Number(physicalProgress), financialProgress: Number(financialProgress), phase, summary, remarks, updatedBy, date, createdAt: project.updatedAt }; db.progressUpdates.unshift(entry); return { project, entry }; }); if (update) res.status(201).json({ project: publicProject(update.project), update: update.entry }); });
app.get("/api/projects/:id/milestones", requireAuth, (req, res) => { const db = readDb(); if (ensureProject(db, req.params.id, res)) res.json({ data: db.milestones.filter((item) => item.projectId === req.params.id) }); });
app.post("/api/projects/:id/milestones", requireAuth, (req, res) => { const { name, description = "", category, startDate, targetDate, progress = 0, status = "Not Started", responsibleTeam = "", remarks = "" } = req.body; const error = validPercent(progress, "Progress"); if (!name || !category || !startDate || !targetDate || error || targetDate < startDate) return res.status(400).json({ message: error || "Name, category, start date and a valid target date are required" }); const milestone = updateDb((db) => { if (!ensureProject(db, req.params.id, res)) return null; const item = { id: uuid(), projectId: req.params.id, name, description, category, startDate, targetDate, dueDate: targetDate, plannedProgress: Number(progress), actualProgress: Number(progress), status: Number(progress) === 100 && status === "Not Started" ? "Completed" : status, responsibleTeam, remarks, createdAt: new Date().toISOString() }; db.milestones.push(item); return item; }); if (milestone) res.status(201).json(milestone); });
app.get("/api/projects/:id/issues", requireAuth, (req, res) => { const db = readDb(); if (ensureProject(db, req.params.id, res)) res.json({ data: (db.issues || []).filter((item) => item.projectId === req.params.id) }); });
app.post("/api/projects/:id/issues", requireAuth, (req, res) => { const { title, category, severity, description, affectedArea = "", reportedBy = req.user.sub, assignedTo = "", dueDate = null, status = "Open", estimatedImpact = "", correctiveAction = "" } = req.body; if (!title || !category || !severity || !description || !reportedBy) return res.status(400).json({ message: "Title, category, severity, description and reporter are required" }); const issue = updateDb((db) => { if (!ensureProject(db, req.params.id, res)) return null; db.issues ||= []; const item = { id: uuid(), projectId: req.params.id, title, category, severity, description, affectedArea, reportedBy, assignedTo, dueDate, status, estimatedImpact, correctiveAction, createdAt: new Date().toISOString() }; db.issues.unshift(item); db.auditSignals.unshift({ id: uuid(), projectId: req.params.id, severity, message: title, status, createdAt: item.createdAt }); return item; }); if (issue) res.status(201).json(issue); });
app.get("/api/projects/:id/report", requireAuth, (req, res) => {
  const db = readDb();
  const project = ensureProject(db, req.params.id, res);
  if (!project) return;
  const data = detailFor(db, project);
  // This report is deliberately laid out as a single A4 oversight sheet.  The
  // former flowing layout allowed PDFKit to insert additional pages whenever a
  // long project record wrapped.
  const pdf = new PDFDocument({ size: "A4", margin: 28, bufferPages: true, compress: true });
  const unavailable = "Data not available";
  const money = (amount) => Number.isFinite(Number(amount)) ? `Rs. ${Number(amount).toLocaleString("en-IN")} Cr` : unavailable;
  const value = (item) => item === undefined || item === null || item === "" ? unavailable : item;
  const sector = project.sector || (project.department?.toLowerCase().includes("metro") ? "Metro Rail / Urban Transport" : unavailable);
  const [district, state] = String(project.location || "").split(",").map((part) => part.trim());
  const revisions = Array.isArray(project.previousRevisions) ? project.previousRevisions : Array.isArray(project.revisions) ? project.revisions : [];
  const issues = [...data.issues, ...data.auditSignals].sort((a, b) => ["Critical", "High", "Medium", "Low"].indexOf(a.severity) - ["Critical", "High", "Medium", "Low"].indexOf(b.severity));
  const crop = (item, limit = 170) => String(value(item)).replace(/\s+/g, " ").slice(0, limit);
  const section = (title, y) => { pdf.roundedRect(28, y, 539, 15, 3).fill("#eef4ff"); pdf.font("Helvetica-Bold").fontSize(7.4).fillColor("#082f7b").text(title.toUpperCase(), 35, y + 4); return y + 19; };
  const text = (label, item, x, y, width) => { pdf.font("Helvetica-Bold").fontSize(6.5).fillColor("#172033").text(`${label}: `, x, y, { width, continued: true, lineBreak: false }); pdf.font("Helvetica").text(crop(item), { continued: false, lineBreak: false }); return y + 10; };
  const entries = (items, makeText, x, y, width, emptyMessage) => { const rows = items.length ? items : [null]; rows.forEach((item, index) => { const body = item ? makeText(item, index) : emptyMessage; const height = pdf.heightOfString(body, { width, fontSize: 6.2, lineGap: 0.4 }); pdf.font("Helvetica").fontSize(6.2).fillColor("#111827").text(body, x, y, { width, lineGap: 0.4 }); y += height + 4; }); return y; };
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="eNirikshan_${project.id}_Project_Report.pdf"`);
  pdf.pipe(res);
  pdf.font("Helvetica-Bold").fontSize(18).fillColor("#082f7b").text("eNirikshan", 28, 28); pdf.fontSize(10).text("Infrastructure Project Monitoring Report", 28, 49);
  pdf.font("Helvetica").fontSize(6.5).fillColor("#475569").text(`Generated: ${new Date().toLocaleString("en-IN")}`, 365, 31, { width: 202, align: "right" });
  let y = 69; y = text("Project", project.name, 28, y, 260); y = text("Project ID", project.id, 305, y - 10, 262); y = text("Location", project.location, 28, y, 260); y = text("Status / risk", `${project.status} / ${project.risk}`, 305, y - 10, 262);
  y += 4; y = section("Project Overview & Classification", y); y = text("Sector", sector, 28, y, 260); y = text("District / state", `${district || unavailable} / ${state || unavailable}`, 305, y - 10, 262); y = text("Implementing agency", project.implementingAgency || project.department, 28, y, 260); y = text("Responsible department", project.department, 305, y - 10, 262); y = text("Description", project.description, 28, y, 539);
  y += 3; y = section("Project Cost, Schedule, Progress & Delays", y); y = text("Sanctioned / expenditure", `${money(project.sanctionedCostCr ?? project.budgetCr)} / ${money(project.expenditureCr ?? project.releasedCr)}`, 28, y, 260); y = text("Financial progress", `${data.fundingProgress ?? unavailable}%`, 305, y - 10, 262); y = text("Predicted final / overrun", `${project.predictedFinalCost ? money(project.predictedFinalCost) : unavailable} / ${project.predictedFinalCost ? money(project.predictedFinalCost - (project.sanctionedCostCr ?? project.budgetCr)) : unavailable}`, 28, y, 260); y = text("Planned / revised completion", `${project.plannedCompletion ?? project.estimatedCompletion ?? unavailable} / ${project.revisedCompletion ?? unavailable}`, 305, y - 10, 262); y = text("Overall / physical target", `${project.overallProgress ?? project.physicalProgress ?? unavailable}% / ${project.physicalProgress ?? unavailable}% (target ${project.targetProgress ?? unavailable}%)`, 28, y, 260); y = text("Schedule slippage", `${project.scheduleLagDays ?? 0} days`, 305, y - 10, 262);
  y += 3; y = section("Physical & Financial Milestones", y); y = entries(data.milestones, (m) => `${m.name} - ${m.status || "Not assessed"}. Category: ${value(m.category)} | Start/target: ${value(m.startDate)} / ${value(m.targetDate || m.dueDate)} | Physical planned/actual: ${m.plannedProgress ?? unavailable}% / ${m.actualProgress ?? unavailable}% | Financial: ${m.financialProgress ?? unavailable}%${m.responsibleTeam ? ` | Team: ${m.responsibleTeam}` : ""}`, 28, y, 539, "No records available.");
  y += 2; y = section("Implementation Issues", y); y = entries(issues, (item) => `${item.title || item.message} - ${item.severity || "Unclassified"} / ${item.status || "Open"}. Category: ${value(item.category)} | Identified: ${value(item.createdAt?.slice(0, 10))} | Affected area: ${value(item.affectedArea)} | Responsible team: ${value(item.assignedTo)} | Corrective action: ${value(item.correctiveAction)} | ${item.description || "No additional details recorded."}`, 28, y, 539, "No implementation issues recorded.");
  y += 2; y = section("Previous Project Revisions & Progress History", y); y = entries(revisions, (r, index) => `Revision ${r.number || r.revisionNumber || index + 1} - ${value(r.date || r.revisionDate)}. Reason: ${value(r.reason)} | Previous/revised cost: ${money(r.previousCost)} / ${money(r.revisedCost)} | Previous/revised completion: ${value(r.previousCompletionDate)} / ${value(r.revisedCompletionDate)} | Approved by: ${value(r.approvedBy)} | Remarks: ${value(r.remarks)}`, 28, y, 539, "No previous project revisions recorded."); y = entries(data.progressHistory, (item) => `${item.date || item.createdAt} - ${item.phase || "Progress update"}. Overall / physical / financial: ${item.overallProgress ?? item.physicalProgress ?? unavailable}% / ${item.physicalProgress ?? unavailable}% / ${item.financialProgress ?? unavailable}% | ${item.summary || item.note || "No summary"}`, 28, y, 539, "No progress history recorded.");
  y += 2; y = section("Project Health Summary", y);
  const concerns = [];
  if (project.physicalProgress < project.targetProgress) concerns.push("Physical progress is below its planned target.");
  if (data.fundingProgress > project.physicalProgress) concerns.push("Financial expenditure is ahead of physical delivery.");
  if (project.scheduleLagDays > 0) concerns.push("The project has recorded schedule slippage.");
  if (issues.some((item) => item.severity === "Critical" && item.status !== "Resolved")) concerns.push("Critical implementation issues remain unresolved.");
  if (data.milestones.some((item) => item.status === "At Risk")) concerns.push("One or more milestones are at risk.");
  pdf.font("Helvetica-Bold").fontSize(7).fillColor(project.risk === "Critical" ? "#dc2626" : "#082f7b").text(`PROJECT HEALTH: ${project.risk?.toUpperCase() || "NOT ASSESSED"}`, 28, y); pdf.font("Helvetica").fontSize(6.2).fillColor("#111827").text(concerns.length ? concerns.map((concern) => `- ${concern}`).join(" ") : "No major concerns recorded from the available project data.", 28, y + 10, { width: 539 });
  const range = pdf.bufferedPageRange();
  for (let page = 0; page < range.count; page += 1) { pdf.switchToPage(page); pdf.fontSize(6.5).fillColor("#64748b").text(`eNirikshan Infrastructure Project Monitoring System  |  Page ${page + 1} of ${range.count}`, 28, 792, { width: 539, align: "center", lineBreak: false }); }
  pdf.end();
});
app.patch("/api/milestones/:id", requireAuth, (req, res) => { const milestone = updateDb((db) => { const item = db.milestones.find((m) => m.id === req.params.id); if (!item) return null; Object.assign(item, req.body); return item; }); if (!milestone) return res.status(404).json({ message: "Milestone not found" }); res.json(milestone); });

app.get("/api/alerts", requireAuth, (req, res) => { const { status = "Open", severity } = req.query; let alerts = readDb().alerts; if (status !== "all") alerts = alerts.filter((a) => a.status === status); if (severity) alerts = alerts.filter((a) => a.severity === severity); res.json({ data: alerts, total: alerts.length }); });
app.post("/api/alerts", requireAuth, (req, res) => { const { projectId, title, description, severity = "Medium" } = req.body; if (!projectId || !title || !description) return res.status(400).json({ message: "projectId, title and description are required" }); const alert = updateDb((db) => { if (!ensureProject(db, projectId, res)) return null; const item = { id: uuid(), projectId, title, description, severity, status: "Open", createdAt: new Date().toISOString(), resolvedAt: null }; db.alerts.unshift(item); return item; }); if (alert) res.status(201).json(alert); });
app.patch("/api/alerts/:id/resolve", requireAuth, (req, res) => { const alert = updateDb((db) => { const item = db.alerts.find((a) => a.id === req.params.id); if (!item) return null; item.status = "Resolved"; item.resolvedAt = new Date().toISOString(); item.resolvedBy = req.user.sub; return item; }); if (!alert) return res.status(404).json({ message: "Alert not found" }); res.json(alert); });
app.post("/api/dashboard/audit-brief", requireAuth, (_req, res) => {
  const db = readDb();
  const projects = db.projects.map((project) => ({ ...publicProject(project), healthIndex: riskScore(project) }));
  const average = (field) => projects.length ? +(projects.reduce((sum, project) => sum + Number(project[field] || 0), 0) / projects.length).toFixed(1) : 0;
  const physicalAverage = average("physicalProgress");
  const fundingAverage = average("fundingProgress");
  const executionGap = +(physicalAverage - fundingAverage).toFixed(1);
  const order = ["Critical", "High", "At Risk", "Medium", "Low"];
  const priorityProjects = projects.filter((project) => project.risk !== "Low").sort((a, b) => order.indexOf(a.risk) - order.indexOf(b.risk));
  const signalsFor = (project) => {
    const signals = [];
    if (project.fundingProgress > project.physicalProgress + 15) signals.push("Financial progress materially ahead of physical progress");
    if (project.scheduleLagDays > 0) signals.push(`Schedule slippage: ${project.scheduleLagDays} days`);
    if (project.physicalProgress < project.targetProgress) signals.push("Physical progress below target");
    const milestones = db.milestones.filter((item) => item.projectId === project.id);
    if (milestones.some((item) => item.status === "At Risk")) signals.push("At-risk milestone recorded");
    const auditSignals = db.auditSignals.filter((item) => item.projectId === project.id && item.status !== "Resolved");
    if (auditSignals.some((item) => /contractor|vendor/i.test(item.message))) signals.push("Contractor/vendor execution variance");
    if (auditSignals.length) signals.push("Unresolved implementation exception");
    return signals;
  };
  const criticalCount = projects.filter((project) => project.risk === "Critical").length;
  const highCount = projects.filter((project) => project.risk === "High" || project.risk === "At Risk").length;
  const attentionCount = priorityProjects.length;
  const elevated = projects.filter((project) => ["Critical", "High", "At Risk"].includes(project.risk) || project.scheduleLagDays > 15);
  const primary = priorityProjects.find((project) => signalsFor(project).length) || projects[0];
  const overall = criticalCount ? "CRITICAL" : highCount ? "HIGH" : "MONITORED";
  const pdf = new PDFDocument({ size: "A4", margin: 28, bufferPages: true, compress: true });
  const color = (risk) => ({ Critical: "#dc2626", High: "#ea580c", "At Risk": "#ea580c", Medium: "#ca8a04", Low: "#059669" }[risk] || "#082f7b");
  const section = (title, x, y, width) => { pdf.roundedRect(x, y, width, 14, 3).fill("#eef4ff"); pdf.font("Helvetica-Bold").fontSize(6.6).fillColor("#082f7b").text(title, x + 5, y + 4, { width: width - 10 }); return y + 18; };
  const copy = (items, x, y, width) => { items.forEach(({ text, ink = "#111827" }) => { const height = pdf.heightOfString(text, { width, fontSize: 5.8, lineGap: 0.5 }); pdf.font("Helvetica").fontSize(5.8).fillColor(ink).text(text, x, y, { width, lineGap: 0.5 }); y += height + 3; }); return y; };
  res.setHeader("Content-Type", "application/pdf"); res.setHeader("Content-Disposition", "attachment; filename=\"eNirikshan_Dashboard_Oversight_Audit_Brief.pdf\""); pdf.pipe(res);
  pdf.font("Helvetica-Bold").fontSize(18).fillColor("#0b2f78").text("eNirikshan", 28, 28); pdf.fontSize(7.8).fillColor("#475569").text("SYSTEM AUTHORITY: PMO CENTRAL OVERSIGHT DESK", 28, 50); pdf.font("Helvetica").fontSize(6.3).fillColor("#64748b").text("National Infrastructure Oversight Dashboard - Early Warning Cell", 28, 62);
  pdf.roundedRect(395, 28, 172, 17, 4).fillAndStroke("#fff1f2", "#ef4444"); pdf.font("Helvetica-Bold").fontSize(7).fillColor("#b91c1c").text(overall === "CRITICAL" ? "CRITICAL ACTION REVIEW" : "OVERSIGHT REVIEW", 402, 33, { width: 158, align: "center" }); pdf.fontSize(10).fillColor("#172033").text("DASHBOARD AUDIT BRIEF", 330, 51, { width: 237, align: "right" }); pdf.font("Helvetica").fontSize(5.9).fillColor("#334155").text("Generated: " + new Date().toLocaleString("en-IN") + " | Demo / Simulated Predictive Assessment", 280, 64, { width: 287, align: "right" });
  pdf.moveTo(28, 78).lineTo(567, 78).lineWidth(1).strokeColor("#172033").stroke(); const alertTop = 89; pdf.roundedRect(28, alertTop, 539, 45, 5).fillAndStroke("#fff4f4", "#fecaca"); pdf.rect(28, alertTop, 4, 45).fill("#e11d48"); pdf.font("Helvetica-Bold").fontSize(6.5).fillColor("#be123c").text("AUTONOMOUS EARLY-WARNING TRIGGER", 39, alertTop + 7); pdf.fontSize(8.2).fillColor("#9f1239").text(primary ? `${primary.name}: ${signalsFor(primary)[0] || "monitoring anomaly detected"}` : "Current monitoring anomaly", 39, alertTop + 17, { width: 510 }); pdf.font("Helvetica").fontSize(5.8).fillColor("#4c0519").text(primary ? `Project ${primary.id} - physical ${primary.physicalProgress}% / target ${primary.targetProgress}% / financial ${primary.fundingProgress}%. ${signalsFor(primary).slice(1).join("; ") || "Review current project telemetry."}` : "Review current dashboard telemetry.", 39, alertTop + 30, { width: 510 });
  const metricY = 146; [[28, "AVG PHYSICAL", physicalAverage + "%", "#1e3a8a"], [165, "AVG FUND RELEASE", fundingAverage + "%", "#0369a1"], [302, "EXECUTION GAP", executionGap + "%", "#dc2626"], [439, "OVERDUE HORIZON", (primary?.scheduleLagDays || 0) + " days", "#ea580c"]].forEach(([x, label, metric, ink]) => { pdf.roundedRect(x, metricY, 128, 35, 4).fillAndStroke("#f8fafc", "#bfdbfe"); pdf.font("Helvetica-Bold").fontSize(5.7).fillColor("#64748b").text(label, x + 5, metricY + 7, { width: 118, align: "center" }); pdf.fontSize(10).fillColor(ink).text(metric, x + 5, metricY + 17, { width: 118, align: "center" }); });
  const colWidth = 171; let left = section("1. EXECUTIVE SUMMARY & TARGET", 28, 193, colWidth); left = copy([{ text: `Overall risk: ${overall}; attention: ${attentionCount}; Critical: ${criticalCount}; High / At Risk: ${highCount}.`, ink: color(overall === "CRITICAL" ? "Critical" : overall === "HIGH" ? "High" : "Low") }, { text: primary ? `Priority: ${primary.id} - ${primary.name} | ${primary.location} | ${primary.risk}. Main signal: ${signalsFor(primary)[0] || "No elevated signal recorded"}.` : "No project data available." }, { text: `Portfolio: physical ${physicalAverage}%; fund release ${fundingAverage}%; execution / financial gap ${executionGap}%. ${executionGap < 0 ? "Financial release is materially ahead of physical execution and should be investigated." : "No material portfolio-wide financial lead is recorded."}` }], 28, left, colWidth); left += 4; left = section("3. CURRENT EARLY-WARNING TRIGGER", 28, left, colWidth); left = copy(primary ? [{ text: `Affected project: ${primary.id} - ${primary.name}. Location: ${primary.location}. Physical / target / financial: ${primary.physicalProgress}% / ${primary.targetProgress}% / ${primary.fundingProgress}%. Detected anomaly: ${signalsFor(primary).join("; ") || "No elevated signal recorded"}.` }] : [{ text: "No project-level early-warning data available." }], 28, left, colWidth); left += 4; left = section("4. PROJECTS REQUIRING ATTENTION", 28, left, colWidth); copy(priorityProjects.map((project) => ({ text: `${project.id} | ${project.name} | ${project.location} | ${project.physicalProgress}% / ${project.targetProgress}% | ${project.risk} | ${project.scheduleLagDays || 0} days | ${signalsFor(project)[0] || "No elevated signal recorded"} | ${project.risk === "Critical" ? "Immediate review" : ["High", "At Risk"].includes(project.risk) ? "Priority review" : "Monitor closely"}`, ink: color(project.risk) })), 28, left, colWidth);
  let middle = section("5. PREDICTIVE TIME-OVERRUN", 212, 193, colWidth); middle = copy([{ text: "Demo / Simulated Predictive Assessment - based on existing Risk Radar, schedule, progress, milestone, and implementation indicators." }, ...elevated.map((project) => { const atRiskMilestones = db.milestones.filter((item) => item.projectId === project.id && item.status === "At Risk").length; return { text: `${project.id} - ${project.name}: risk ${project.risk}; schedule slippage ${project.scheduleLagDays || 0} days; physical ${project.physicalProgress}% vs target ${project.targetProgress}%; at-risk milestones ${atRiskMilestones}; ${signalsFor(project).join("; ") || "No elevated signal recorded"}.`, ink: color(project.risk) }; })], 212, middle, colWidth); middle += 4; middle = section("6. IMPLEMENTATION RISK ANALYSIS", 212, middle, colWidth); copy(priorityProjects.map((project) => { const implementation = [...db.auditSignals, ...(db.issues || [])].filter((item) => item.projectId === project.id && item.status !== "Resolved").map((item) => item.message || item.title).filter(Boolean); return { text: `${project.id}: ${implementation.length ? implementation.join("; ") : "No additional implementation issue recorded."}` }; }), 212, middle, colWidth);
  let right = section("7. RECOMMENDED OVERSIGHT ACTIONS", 396, 193, colWidth); right = copy(["Review Critical projects immediately using the current project evidence.", "Investigate projects where financial progress materially exceeds physical execution.", "Review delayed or at-risk milestones and recorded implementation bottlenecks.", "Review projects with significant schedule slippage and elevated time-overrun risk.", "Continue targeted monitoring; no audit action is claimed as completed by this report."].map((text) => ({ text: "- " + text })), 396, right, colWidth); right += 4; right = section("AUDIT CONCLUSION", 396, right, colWidth); copy([{ text: "Current monitoring data indicates execution and schedule risks requiring targeted project-level oversight. Projects showing physical-financial mismatch, milestone slippage, implementation exceptions, or elevated time-overrun risk should receive priority review." }], 396, right, colWidth);
  const pages = pdf.bufferedPageRange(); for (let index = 0; index < pages.count; index += 1) { pdf.switchToPage(index); pdf.fontSize(6.2).fillColor("#64748b").text("eNirikshan Central Oversight Desk - Dashboard Audit Record", 28, 792, { lineBreak: false }); pdf.text("Document Ref: DASH-AUD-" + new Date().toISOString().slice(0, 10).replace(/-/g, "") + " | Page " + (index + 1) + " of " + pages.count, 290, 792, { width: 277, align: "right", lineBreak: false }); } pdf.end();
});
app.get("/api/risk-radar", requireAuth, (_req, res) => { const projects = readDb().projects.map((project) => ({ ...publicProject(project), healthIndex: riskScore(project) })); const tiers = ["Critical", "High", "Medium", "Low"]; res.json({ total: projects.length, tiers: tiers.map((risk) => ({ risk, count: projects.filter((p) => p.risk === risk).length, share: projects.length ? Math.round((projects.filter((p) => p.risk === risk).length / projects.length) * 100) : 0 })), topRisks: projects.sort((a, b) => b.healthIndex - a.healthIndex).slice(0, 10), triggers: ["Financial progress outpaces physical work", "Schedule slippage exceeds 15 days", "Vendor execution variance", "Unresolved audit exception"] }); });
app.post("/api/risk-radar/audit-brief", requireAuth, (req, res) => {
  const { tiers = [], triggers = [], filteredProjectIds = [] } = req.body || {};
  const projects = readDb().projects.map((project) => ({ ...publicProject(project), healthIndex: riskScore(project) }));
  const scoped = filteredProjectIds.length ? projects.filter((project) => filteredProjectIds.includes(project.id)) : projects;
  const pdf = new PDFDocument({ margin: 48, bufferPages: true });
  const color = (risk) => ({ Critical: "#dc2626", High: "#ea580c", Medium: "#ca8a04", Low: "#059669" }[risk] || "#082f7b");
  const heading = (title) => { if (pdf.y > 690) pdf.addPage(); pdf.moveDown(.7).font("Helvetica-Bold").fontSize(14).fillColor("#082f7b").text(title).moveDown(.3).fillColor("#111827"); };
  const line = (text, ink = "#111827") => pdf.font("Helvetica").fontSize(10).fillColor(ink).text(text).fillColor("#111827").moveDown(.25);
  res.setHeader("Content-Type", "application/pdf"); res.setHeader("Content-Disposition", "attachment; filename=\"eNirikshan_Audit_Brief.pdf\""); pdf.pipe(res);
  pdf.font("Helvetica-Bold").fontSize(23).fillColor("#082f7b").text("eNirikshan"); pdf.fontSize(12).text("Infrastructure Project Monitoring & Oversight").moveDown(.4); pdf.fontSize(17).text("OPERATIONAL RISK AUDIT BRIEF"); pdf.font("Helvetica").fontSize(12).text("Risk Radar & Early Warning Assessment").moveDown();
  line("Report Date: " + new Date().toLocaleString("en-IN")); line("Reporting Scope: Current Risk Radar telemetry selection"); line("Telemetry Status: LIVE TELEMETRY");
  const activeTotal = tiers.reduce((sum, tier) => sum + Number(tier.count || 0), 0) || scoped.length; const critical = tiers.find((tier) => tier.risk === "Critical"); const high = tiers.find((tier) => tier.risk === "High");
  heading("SECTION 1 - EXECUTIVE RISK SUMMARY"); line("Total Active Projects: " + activeTotal); tiers.forEach((tier) => line((tier.label || tier.risk) + ": " + tier.count + " projects (" + tier.share + "%) - " + (tier.delta || "Current status"), color(tier.risk))); line("Risk interpretation: " + ((Number(critical?.count || 0) + Number(high?.count || 0)) > 0 ? "the current portfolio contains a material concentration of Critical and High risk projects requiring focused oversight." : "the current selection has no Critical or High risk tier count."));
  heading("SECTION 2 - PREDICTIVE TELEMETRY SYNTHESIS"); line("Model: MODEL V4.8"); line("Confidence: 94.2%"); line("Data / model status: DEMO / SIMULATED PREDICTIVE OUTPUT"); line(scoped.filter((project) => project.risk === "Critical" || project.risk === "High").length + " available project records are in Critical or High risk tiers. This is a demonstrative monitoring signal, not a validated production ML prediction.");
  heading("SECTION 3 - RISK TIER ANALYSIS"); line("Risk Tier | Projects | Share | Current Signal | Oversight Priority"); tiers.forEach((tier) => { const priorityLabel = tier.risk === "Critical" ? "Immediate" : tier.risk === "High" ? "High" : tier.risk === "Medium" ? "Moderate" : "Routine"; line((tier.label || tier.risk) + " | " + tier.count + " | " + tier.share + "% | " + (tier.delta || "Monitored") + " | " + priorityLabel, color(tier.risk)); });
  heading("RISK DISTRIBUTION"); tiers.forEach((tier) => { const width = Math.max(0, Math.min(100, Number(tier.share || 0))) * 3.4; line((tier.label || tier.risk) + " — " + tier.share + "%"); pdf.rect(48, pdf.y + 3, 340, 9).fill("#e5e7eb"); pdf.rect(48, pdf.y - 6, width, 9).fill(color(tier.risk)); pdf.moveDown(.9); });
  heading("SECTION 4 - TOP PREDICTIVE / EARLY-WARNING TRIGGERS"); line("Trigger | Affected Projects | Oversight Significance | Review Priority"); triggers.forEach((trigger, index) => { const priorityLabel = trigger.count > 0 ? "Review" : "Monitor"; line(String(index + 1).padStart(2, "0") + " " + trigger.name + " | " + trigger.count + " | " + (trigger.count > 0 ? "Active early-warning signal" : "No current match") + " | " + priorityLabel); });
  heading("SECTION 5 - PROJECT-LEVEL RISK OBSERVATIONS"); line("Project | ID | Location | Risk Tier | Physical Progress | Key Risk Observation | Priority"); scoped.sort((a, b) => b.healthIndex - a.healthIndex).forEach((project) => { const financialProgress = project.fundingProgress ?? 0; const observation = project.scheduleLagDays > 15 ? "Schedule slippage exceeds 15 days" : financialProgress > project.physicalProgress + 15 ? "Financial progress is materially ahead of physical progress" : project.physicalProgress < project.targetProgress ? "Physical progress is below target" : "Continue routine monitoring"; const priorityLabel = project.risk === "Critical" ? "Immediate" : project.risk === "High" ? "High" : "Monitor"; line(project.name + " | " + project.id + " | " + project.location + " | " + project.risk + " | " + project.physicalProgress + "% | " + observation + " | " + priorityLabel, color(project.risk)); });
  heading("SECTION 6 - EARLY WARNING ASSESSMENT"); const active = triggers.filter((trigger) => trigger.count > 0); (active.length ? active : [{ name: "No active trigger matches", count: 0 }]).forEach((trigger) => line(trigger.name + ": " + trigger.count + " project(s) require review. The signal can indicate potential time/cost overrun risk and should be reviewed alongside project milestones and implementation evidence."));
  heading("SECTION 7 - OVERSIGHT PRIORITIES"); const priority = scoped.filter((project) => project.risk === "Critical" || project.risk === "High").sort((a, b) => b.healthIndex - a.healthIndex); priority.length ? priority.forEach((project) => line(project.id + " - " + project.name + " | " + project.location + " | " + project.risk + " | Health score " + project.healthIndex + " | Physical " + project.physicalProgress + "% | Schedule lag " + project.scheduleLagDays + " days", color(project.risk))) : line("No Critical or High project records are available within the selected telemetry scope.");
  heading("EARLY INTERVENTION PRIORITIES"); const recommendations = []; if (active.some((trigger) => trigger.name.includes("Financial"))) recommendations.push("Review projects where expenditure is significantly ahead of physical progress."); if (active.some((trigger) => trigger.name.includes("Schedule"))) recommendations.push("Escalate projects with prolonged schedule slippage."); if (priority.length) recommendations.push("Monitor Critical and High risk projects requiring immediate attention."); (recommendations.length ? recommendations : ["Continue monitoring the current telemetry criteria."]).forEach((item) => line("• " + item));
  heading("SECTION 8 - AUDIT OBSERVATIONS"); const criticalShare = critical?.share || 0; line(criticalShare + "% of active projects are classified as Critical in the current dashboard summary."); line("Financial/physical progress variance, schedule delay, milestone slippage, and unresolved exceptions are monitored as early-warning indicators when present."); line("Projects in higher risk tiers require closer oversight based on the current Risk Radar selection.");
  heading("SECTION 9 - OVERALL ASSESSMENT"); const overall = priority.some((project) => project.risk === "Critical") ? "CRITICAL" : priority.length ? "HIGH" : "MONITORED"; line("Overall Risk Status: " + overall, overall === "CRITICAL" ? "#dc2626" : "#ea580c"); line("Projects requiring immediate attention: " + priority.length); line("The current risk concentration and early-warning signals support continued monitoring of physical-financial alignment, schedule performance, milestones, and implementation bottlenecks.");
  pdf.moveDown(.7).fontSize(8).fillColor("#64748b").text("Demo-based audit brief generated from the eNirikshan Risk Radar monitoring dataset. Predictive outputs are demonstrative unless connected to a validated production ML model.");
  const pages = pdf.bufferedPageRange(); for (let index = 0; index < pages.count; index += 1) { pdf.switchToPage(index); pdf.fontSize(8).fillColor("#64748b").text("eNirikshan Infrastructure Project Monitoring System  |  CONFIDENTIAL — INTERNAL OVERSIGHT USE  |  Page " + (index + 1) + " of " + pages.count, 48, 730, { align: "center", lineBreak: false }); } pdf.end();
});
app.post("/api/assistant/query", requireAuth, (req, res) => { const { message, conversationId = uuid() } = req.body; if (!message?.trim()) return res.status(400).json({ message: "message is required" }); const db = readDb(); const p104 = db.projects.find((p) => p.id === "P104"); const answer = `Current portfolio evidence: ${p104.name} is ${p104.risk.toLowerCase()} with ${p104.physicalProgress}% physical progress against ${p104.targetProgress}% target, ₹${p104.releasedCr} Cr released, and ${p104.scheduleLagDays} days of schedule slippage. Recommended immediate action: dispatch a contract and progress audit, then review milestone dependencies.`; updateDb((data) => { data.conversations.push({ id: uuid(), conversationId, userId: req.user.sub, question: message.trim(), answer, createdAt: new Date().toISOString() }); }); res.json({ conversationId, answer, sources: [{ projectId: "P104", label: "Project telemetry" }] }); });

app.use((err, _req, res, _next) => { if (err.message === "Project ID already exists") return res.status(409).json({ message: err.message }); console.error(err); res.status(500).json({ message: "Unexpected server error" }); });
app.use((_req, res) => res.status(404).json({ message: "Endpoint not found" }));
await initialiseStore();
app.listen(port, () => console.log(`ProjectPulse API listening on http://localhost:${port}`));
